setwd("c:/Rtest")
install.packages(c("KoNLP", "arules", "igraph", "combinat"))
library(KoNLP)
library(arules)
library(igraph)
library(combinat)
f <- file("tax.txt", encoding="UTF-8")
fl <- readLines(f)
close(f)
head(fl, 10)
tran <- Map(extractNoun, fl)
tran <- unique(tran)
tran <- sapply(tran, unique)
tran <- sapply(tran, function(x) {Filter(function(y) {nchar(y) <= 4 && nchar(y) 1 && is.hangul(y)},x)} )
tran <- Filter(function(x){length(x) >= 2}, tran)
names(tran) <- paste("Tr", 1:length(tran), sep="")
names(tran)
wordtran <- as(tran, "transactions")
wordtran
wordtab <- crossTable(wordtran)
wordtab
ares <- apriori(wordtran, parameter=list(supp=0.07, conf=0.05))
inspect(ares)
rules <- labels(ares, ruleSep=" ")
rules <- sapply(rules, strsplit, " ", USE.NAMES=F)
rulemat <- do.call("rbind", rules)
ruleg <- graph.edgelist(rulemat[-c(1:16),],directed=F)
plot.igraph(ruleg, vertex.label=V(ruleg)$name,
            vertex.label.cex=0.5, vertex.size=20,
            layout=layout.fruchterman.reingold.grid)
closen <- closeness(ruleg)
plot(closen, col="red",xaxt="n", lty="solid", type="b", xlab="´Ü¾î", ylab="closeness")
points(closen, pch=16, col="navy")
axis(1, seq(1, length(closen)), V(ruleg)$name, cex=5)